# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 016b600b8e3a535ce9db2137c77155fb741fd6e9bf89d6726cfa3edd1ee383b3415693b9eb926eee119c4efa1dcc354d76694019d7b47aa7278081b5430d57fd

test:
  secret_key_base: 750e750973334130bb498347aeff439e4be1d9a699abf6d6574e37c50e3efdc675bb78d53ac17f4855451424af2bc42f95c7350f5a46583446254a0c9dff4ee8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
